# example netlify.toml
[build]
command = "npm install"

[dev]
functions = "netlify/functions"

[functions]
external_node_modules = ["express", "geoip-lite"]
node_bundler = "esbuild"

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"
